export const ADD_INGREDIENT='ADD_INGREDIENT'
export const REMOVE_INGREDIENT='REMOVE_INGREDIENT'
export const INIT_INGREDIENTS='INIT_INGREDIENTS'

export const FETCH_ORDERS='FETCH_ORDERS';
export const RESET_PRICE='RESET_PRICE';
export const CLEAR_INGREDIENTS='CLEAR_INGREDIENTS';